name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install cppunit
      run: sudo apt install -y libcppunit-dev
    - name: make build dir
      run: mkdir build && cd build
    - name: configure
      run: cd build && cmake .. 
    - name: make
      run: cd build && cmake --build .
    - name: run test
      run: cd build && ./helloworld
#    - name: make test
#      run: make test
